name: Checkmarx
    
on:
   workflow_dispatch:
#   push:
#     branches: ['master']
#   pull_request:
#     branches: ['master']

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                    repository: rpolama/AppSecToolsIntegration
            - name: Checkmarx AST Github Action
              uses: Checkmarx/ast-github-action@2.0.9
              with:
                base_uri: https://ast.checkmarx.net/
                cx_tenant: servicenow-nfr
                cx_client_id: ${{ secrets.CX_CLIENT_ID }}
                cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
              id: checkmarx
            - name: log checkmarx output
              run: |
                echo "${{join(steps.checkmarx.outputs.*, ', ')}}"
              
            #- name: Checkmarx CxFlow Action
            # You may pin to the exact commit or the version.
            # uses: checkmarx-ts/checkmarx-cxflow-github-action@49d8269b14ca87910ba003d47a31fa0c7a11f2fe
              #uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.5
              #with:
                
                    # Provide Checkmarx URL
                    #checkmarx_url: https://ast.checkmarx.net/
                    # Select a Checkmarx Team (optional)
                    # team: /CxServer/servicenow
                    # Provide Checkmarx Username
                    #checkmarx_username: ramachandrarao.p
                    # Provide Checkmarx Password
                    #checkmarx_password: ${{secrets.CX_PASSWORD_OLD}}
                    # Provide Checkmarx Client Secret
                    #checkmarx_client_secret: ${{secrets.CX_SECRET_OLD}} 
                    # Select a Checkmarx Project
                    #project: GitHubDemoProject
                    # Vulnerability Scanners (sast, sca, cxgo)
                    #scanners: sast
                    #params: --namespace=rpolama --repo-name=AppSecToolsIntegration --branch=master --cx-flow.filterSeverity --cx-flow.filterCategory  --checkmarx.disable-clubbing=true
