name: Veracode
    
on:
#push:
#branches: ['master']
#pull_request:
#branches: ['master']
  workflow_dispatch:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                repository: rpolama/AppSecToolsIntegration
                    
            - name: build Repo
              run: mvn clean install
                    
            - name: Veracode Upload And Scan
              # You may pin to the exact commit or the version.
              # uses: veracode/veracode-uploadandscan-action@35794dab9fbcd28fac19e44963f80646b27f4a7f
              uses: veracode/veracode-uploadandscan-action@0.2.4
              with:
                    appname: 'GitHub Vera POC'
                    createprofile: false
                    filepath: AppSecToolsIntegration/target
                    version: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
                    vid: ${{secrets.VERACODE_API_ID}}
                    vkey: ${{secrets.VERACODE_API_KEY}}
